/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_content_delivery_bucket: "podscribe-20190721210710-hostingbucket-userpool",
  aws_content_delivery_bucket_region: "us-east-1",
  aws_content_delivery_url: "https://d283xfgcqu27ur.cloudfront.net",
  aws_cognito_identity_pool_id: "us-east-1:5dd3a2a7-8307-465e-923f-5c3b9fd4412d",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_8Aaf3IR11",
  aws_user_pools_web_client_id: "2rmes4u163rf6jqma5s9nmh2au",
  oauth: {
    domain: "podscribe-userpool.auth.us-east-1.amazoncognito.com",
    scope: ["phone", "email", "openid", "profile", "aws.cognito.signin.user.admin"],
    redirectSignIn: "http://localhost:3000/",
    redirectSignOut: "http://localhost:3000/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_AND_IDENTITY_POOLS",
};

export default awsmobile;
