import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Auth } from "aws-amplify";
import useAuth from "../utils/useAuth";

export default function Home() {
  const { user, loading } = useAuth();
  console.log(user, loading);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {loading && <p className={styles.loading}>Loading...</p>}

        {!user && (
          <button
            onClick={() => {
              Auth.federatedSignIn();
            }}
          >
            Login
          </button>
        )}
        {user && !loading && (
          <>
            {user.attributes.email}
            <button
              onClick={() => {
                Auth.signOut();
              }}
            >
              Logout
            </button>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Podverifi
        </a>
      </footer>
    </div>
  );
}
